{% set name = "doc2dash" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5456ee60cce489dd03f6e236b2d997f949d17de3a0fce5e6be3c262493efa1ee

build:
  noarch: python
  number: 0
  entry_points:
    - doc2dash = doc2dash.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools>=40.6.0
    - wheel
  run:
    - python
    - sphinx
    - attrs
    - beautifulsoup4
    - click
    - colorama
    - six
    - zope.interface

test:
  imports:
    - doc2dash
    - doc2dash.parsers
  source_files:
    - tests
  commands:
    - pytest
  requires:
    - pytest
    - mock
    - coverage

about:
  home: https://pypi.org/project/doc2dash/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Convert docs to Dash.app
  description: "doc2dash: Create docsets for Dash.app and clones\n================================================\n\n.. image:: https://readthedocs.org/projects/doc2dash/badge/?version=stable\n   :target: https://doc2dash.readthedocs.io/en/stable/?badge=stable\n   :alt: Documentation Status\n\n.. image:: https://travis-ci.org/hynek/doc2dash.svg?branch=master\n\
    \   :target: https://travis-ci.org/hynek/doc2dash\n\n.. image:: https://codecov.io/github/hynek/doc2dash/branch/master/graph/badge.svg\n  :target: https://codecov.io/github/hynek/doc2dash\n  :alt: Test Coverage\n\n.. begin\n\n\n``doc2dash`` is an MIT-licensed extensible `Documentation Set`_ generator intended to be used\
    \ with the `Dash.app`_ API browser for macOS or one of its many *free* `clones <https://doc2dash.readthedocs.io/en/latest/installation.html#viewer>`_ for all relevant platforms.\n\nIf you’ve never heard of Dash.app, you’re missing out:\ntogether with ``doc2dash`` it’s all your API documentation at your fingertips!\n\n\
    ``doc2dash``\\ ’s documentation lives at `Read the Docs`_, the code on GitHub_.\nIt’s tested on Python 2.7, 3.4+, and PyPy.\nBoth Linux and macOS are tested although certain features are only available on macOS.\n\n\n.. _`Documentation Set`: https://developer.apple.com/legacy/library/documentation/DeveloperTools/Conceptual/Documentation_Sets/010-Overview_of_Documentation_Sets/docset_overview.html#//apple_ref/doc/uid/TP40005266-CH13-SW6\n\
    .. _`Dash.app`: https://kapeli.com/dash/\n.. _`Read the Docs`: https://doc2dash.readthedocs.io/\n.. _`GitHub`:  https://github.com/hynek/doc2dash\n\n\nRelease Information\n===================\n\n2.2.0 (2017-06-12)\n------------------\n\n- ``InterSphinxParser`` is now open to extension.\n  `#59 <https://github.com/hynek/doc2dash/pull/59>`_\n\
    - Support a ``--parser`` option to force the use of a custom parser class.\n  `#60 <https://github.com/hynek/doc2dash/pull/60>`_\n\n`Full changelog <https://doc2dash.readthedocs.io/en/stable/changelog.html>`_.\n\nAuthors\n=======\n\n``doc2dash`` is written and maintained by Hynek Schlawack.\n\nThe development is kindly\
    \ supported by `Variomedia AG <https://www.variomedia.de/>`_.\n\nA full list of contributors can be found on `GitHub's overview <https://github.com/hynek/doc2dash/graphs/contributors>`_.\n\n\n"
  doc_url: https://doc2dash.readthedocs.io/
  dev_url: https://github.com/hynek/doc2dash

extra:
  recipe-maintainers:
    - pbronez
    - hoishing
