{% set version = "3.1.0" %}

package:
  name: doc2dash
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/doc2dash/doc2dash-{{ version }}.tar.gz
  sha256: 37f61c8d8f6a955d2466b9c073eb2bff44cc54352bf817afb48a3ac8aef6d594

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - doc2dash = doc2dash.__main__:main

requirements:
  host:
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - attrs >=23.2
    - beautifulsoup4
    - click
    - python >={{ python_min }}
    - rich

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - doc2dash
  commands:
    - pip check
    - doc2dash --version
    - doc2dash --help
    - pytest -vv --cov=doc2dash --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=99

about:
  summary: |
    doc2dash is an extensible Documentation Set (docset) generator that helps you
    to have documentation for all your favorite APIs in Dash.app-compatible API browsers.
  home: https://doc2dash.hynek.me
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/hynek/doc2dash
  description: |
    An API browser is an application that runs locally on your computer and allows
    you to search various API docs by pressing a key combination and starting to
    type (I have bound it to ⌥Space bar and can’t write code without it).

    The most common ones – [Dash](https://kapeli.com/dash) (macOS) and
    [Zeal](https://zealdocs.org) (Windows and Linux) – come with **many** docsets
    out of the box, but they can never offer you docsets for *every* package
    you’ll ever use.

    This is where *doc2dash* comes in:
    It takes your offline documentation and converts it into an indexed format
    that API browsers can read and search (very fast!).

    Currently it supports all known *intersphinx*-based documentation systems
    like [Sphinx](https://www.sphinx-doc.org/),
    [*pydoctor*](https://github.com/twisted/pydoctor), or
    [MkDocs](https://www.mkdocs.org) (with
    [*mkdocstrings*](https://mkdocstrings.github.io)).

    While *doc2dash* is a Python project, the support is **not** limited to
    Python-related formats.

    It’s also extendable:
    [**you** can write your own parser](https://doc2dash.hynek.me/en/latest/extending/)!

extra:
  recipe-maintainers:
    - pbronez
    - hoishing
    - bollwyvl
