{% set version = "3.0.0" %}

package:
  name: doc2dash
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/doc2dash/doc2dash-{{ version }}.tar.gz
  sha256: 5456ee60cce489dd03f6e236b2d997f949d17de3a0fce5e6be3c262493efa1ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - doc2dash = doc2dash.__main__:main

requirements:
  host:
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.8
  run:
    - attrs >=21.3
    - beautifulsoup4
    - click
    - python >=3.8
    - rich

test:
  source_files:
     - tests
  requires:
    - pip
    - pytest-cov
  imports:
    - doc2dash
  commands:
    - pip check
    - doc2dash --version
    - doc2dash --help
    - pytest -vv --cov=doc2dash --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=99

about:
  summary: |
    doc2dash is an extensible Documentation Set (docset) generator that helps you
    to have documentation for all your favorite APIs in Dash.app-compatible API browsers.
  home: https://doc2dash.hynek.me
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/hynek/doc2dash

extra:
  recipe-maintainers:
    - pbronez
    - hoishing
    - bollwyvl
